### ISSUE TITLE
Matplotlib 3.5.x breaks some plots

### ISSUE THREAD

**Issue by robbievanleeuwen** [robbievanleeuwen/section-properties#159]
Matplotlib >= 3.5 seems to break plot sizes and patches in *sectionproperties*. Example below:

```python
import sectionproperties.pre.library.steel_sections as steel_sections
from sectionproperties.analysis.section import Section

# Create a 150x100x6 RHS on its side
geometry = steel_sections.rectangular_hollow_section(d=100, b=150, t=6, r_out=15, n_r=8)

# Create a mesh and section object. For the mesh, use a maximum area of 2
geometry.create_mesh(mesh_sizes=[2])
section = Section(geometry)

# Perform a geometry and warping analysis
section.calculate_geometric_properties()
section.calculate_warping_properties()

# Perform a stress analysis with Mx = 5 kN.m; Vx = 10 kN and Mzz = 3 kN.m
case1 = section.calculate_stress(Mxx=5e6, Vx=10e3, Mzz=3e6)
```

Plot sizes are much smaller and patches are far less transparent(?) by default (images have been scaled in ratio to their original size - best to view on computer screen but image width and height are both approximately halved):

```python
section.plot_mesh()
```

**matplotlib==3.4.2**

<img src="https://user-images.githubusercontent.com/18841910/147849629-e8cfda1f-533b-4f4c-b943-17de6e9eb748.png" width="666" />

**matplotlib==3.5.1**

<img src="https://user-images.githubusercontent.com/18841910/147849642-83e768f2-4efc-4c19-af64-beb9e1030cfb.png" width="347" />

```python
case1.plot_stress_vm()
```

**matplotlib==3.4.2**

<img src="https://user-images.githubusercontent.com/18841910/147849672-7aeb61e5-bf2f-4be2-bf21-23ec2430182a.png" width="666" />

**matplotlib==3.5.1**

<img src="https://user-images.githubusercontent.com/18841910/147849677-a3fbc1d9-9e33-4166-88d3-dd6459ca5619.png" width="347" />

Is the answer to, for now, require matplotlib < 3.5? Patches may be able to be sorted by passing an alpha value as an argument but not sure how to handle the plot size reducing? Haven't had much of a look at it yet thought...

**Comment by Spectre5** [comment]
Is this in v2 branch or current one?  Does it happen in both?

**Comment by Spectre5** [comment]
Also, what is the actual image output sizes in pixes, width and height?

**Comment by robbievanleeuwen** [comment]
@Spectre5 yes this is in the v2 branch. Interestingly don't have the sizing issue with the `master` branch, but do have the transparency issue. This is a good clue!

Currently with the default figure sizes in v2 (500px) and saving by clicking the save icon, 3.4.2 saves as a 1332 x 998 image and 3.5.1 saves as a 693 x 518 image. Kind of odd as my macOS resolution is 1440x900 but I have a 'retina' display of 2560x1600 so maybe there's something funny going on there that I don't understand. The 3.5.1 image takes up about a fifth of the width of my display whereas the  3.4.2 is just under half. Will have a deeper dig.

**Comment by Spectre5** [comment]
Maybe something to do with changing figure size before the dpi in the post function?

**Comment by Spectre5** [comment]
With a "size" of 500px (your default), what size do you expect the output to be?  I guess I'd assume 500 which is closer to the 3.5.1 output...

I think it would be easier and more clear to define the size and dpi as parts of the subplots call, and to allow a user to specify them exactly.  Further, I think the same for those font sizes.  If I'm adding the output image to some report, then I probably want to specify the exact font size so that it matches the documents font size and potentially I'd want to define the exact figure size too.

**Comment by robbievanleeuwen** [comment]
My thoughts on this are:

- All plotting functions return ``(fig, ax)`` - this allows users to make changes to almost all matplotlib properties e.g. figure size, dp, lineweights, font sizes etc.
- We should remove all plotting options that aren't necessary to *sectionproperties*, i.e. ``size`` and ``dpi``
- This will fix the sizing issues in this issue and changes to the patches call should fix the transparency.
- I note there was a previous PR #63 that looked to make some changes to the way plotting in *sectionproperties* operated. Unfortunately this was closed before I could review but I'm open to having a look at these ideas again post v2.

@connorferster @Spectre5 what are your thoughts on the above?

**Comment by Spectre5** [comment]
Also note that the plotting only PR you linked to still shows the diffs, so you can scroll down the python files and see what it did, which way be easier than trying to find those parts in the other all encompassing PR.

**Comment by normanrichardson** [comment]
I think seaborn does this also, for example [swarmplot](https://seaborn.pydata.org/generated/seaborn.swarmplot.html#seaborn.swarmplot):
>kwargs: key, value mappings
>
>    Other keyword arguments are passed through to matplotlib.axes.Axes.scatter().

**Comment by Spectre5** [comment]
Yes, another point is that it really isn't necessary to return the figure along with the axes as it is very easy to get the figure if you want it (`ax.get_figure()`).  This is why some libraries, like seaborn, only return the axes.

Alternatively, you could return only the figure and then get the axes from the figure.  But it is much more common in other libraries to return just the axes.

**Comment by robbievanleeuwen** [comment]
Thanks for all your input! I'll have a look at incorporating some of the code from #63, thanks again to @Spectre5!

Once this issue and #164 are closed I think we'll be ready for v2!

**Comment by robbievanleeuwen** [comment]
Fixed with #168.
